name: lighthouse-ci

on: 
  pull_request:
    branches:
      - test2


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - run: echo ::set-env name=PULL_NUMBER::$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
      - run: echo $PULL_NUMBER
      - run: npm install
      - name: testing script
        run: node app.js